//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiskImager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiskImager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All images.
        /// </summary>
        public static string AllImages {
            get {
                return ResourceManager.GetString("AllImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while cloning.
        /// </summary>
        public static string CloneError {
            get {
                return ResourceManager.GetString("CloneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string CloneTitle {
            get {
                return ResourceManager.GetString("CloneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This utility will now clone data
        ///
        ///from: {0}
        ///to: {1}.
        ///
        ///This operation is not reversible and will replace ALL DATA of the selected destination.
        ///Do you confirm this is what you want?.
        /// </summary>
        public static string CloneWarningFormat {
            get {
                return ResourceManager.GetString("CloneWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source size ({0}) is bigger than destination size ({1})
        ///The cloning operation is likely to fail
        ///Do you want to continue anyway?.
        /// </summary>
        public static string CloneWarningSizeFormat {
            get {
                return ResourceManager.GetString("CloneWarningSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all partitions of disk {0} for a total of {1}.
        /// </summary>
        public static string DiskReadFormat {
            get {
                return ResourceManager.GetString("DiskReadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disk {0} with a total of {1} space available.
        /// </summary>
        public static string DiskWriteFormat {
            get {
                return ResourceManager.GetString("DiskWriteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange sides.
        /// </summary>
        public static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} raw image.
        /// </summary>
        public static string ImageRawReadFormat {
            get {
                return ResourceManager.GetString("ImageRawReadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raw image with a maximum size of {0}.
        /// </summary>
        public static string ImageRawWriteFormat {
            get {
                return ResourceManager.GetString("ImageRawWriteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} xz image that will be decompressed to a {1} image.
        /// </summary>
        public static string ImageXZReadFormat {
            get {
                return ResourceManager.GetString("ImageXZReadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xz image with a maximum size of {0}.
        /// </summary>
        public static string ImageXZWriteFormat {
            get {
                return ResourceManager.GetString("ImageXZWriteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} zip image that will be decompressed to a {1} image.
        /// </summary>
        public static string ImageZipReadFormat {
            get {
                return ResourceManager.GetString("ImageZipReadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zip image with a maximum size of {0}.
        /// </summary>
        public static string ImageZipWriteFormat {
            get {
                return ResourceManager.GetString("ImageZipWriteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount points.
        /// </summary>
        public static string MountPoint {
            get {
                return ResourceManager.GetString("MountPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No destination selected.
        /// </summary>
        public static string NoDestinationSelected {
            get {
                return ResourceManager.GetString("NoDestinationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source selected.
        /// </summary>
        public static string NoSourceSelected {
            get {
                return ResourceManager.GetString("NoSourceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.0}% at {1}/s ({2}/{3}).
        /// </summary>
        public static string ProgressionFormat {
            get {
                return ResourceManager.GetString("ProgressionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B,KB,MB,GB,TB.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
    }
}
